services:
  Proglab\SelligentClientBundle\Service\SelligentClient:
    class: Proglab\SelligentClientBundle\Service\SelligentClient
    arguments:
      $individual_url: '%env(APISELLIGENTCLIENT_INDIVIDUAL_URL)%'
      $broadcast_url: '%env(APISELLIGENTCLIENT_BROADCAST_URL)%'
      $login: '%env(APISELLIGENTCLIENT_LOGIN)%'
      $password: '%env(APISELLIGENTCLIENT_PASSWORD)%'
    public: selligent_client